[build]
target = "aarch64-unknown-none"

[target.'cfg(target_arch="aarch64")']
rustflags = ["-Clink-arg=-Tsrc/arch/aarch64/link.ld"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
