#! /usr/bin/zsh
# Reference
# https://cdn.kernel.org/pub/linux/kernel/people/will/docs/qemu/qemu-arm64-howto.html

# if [ ! -f esp/EFI/boot/bootaa64.efi ]; then
#   mkdir -p esp/EFI/boot
#   ln -s ../../../../target/aarch64-unknown-uefi/debug/cosmos.efi esp/EFI/boot/bootaa64.efi
# fi

qemu-system-aarch64 -M virt  \
      -machine virtualization=true -machine virt,gic-version=3  \
      -cpu cortex-a76 -smp 4 -m 8192           \
      -device virtio-scsi-pci,id=scsi0              \
      -object rng-random,filename=/dev/urandom,id=rng0      \
      -device virtio-rng-pci,rng=rng0               \
      -device virtio-net-pci,netdev=net0                \
      -netdev user,id=net0,hostfwd=tcp::8022-:22            \
      -semihosting \
      -display none \
      -kernel ../target/aarch64-unknown-none/debug/cosmos \
      -drive if=virtio,format=qcow2,file=disk.img           \
      -nographic                            

      # -S -gdb tcp::1234 \
      # -device guest-loader,addr=0x48000000,initrd=libhermit.a \
      # -device guest-loader,addr=0x48000000,initrd=../target/aarch64-unknown-none/debug/cosmos \
      # -machine dumpdtb=qemu.dtb \
