#! /usr/bin/zsh
# Reference
# https://cdn.kernel.org/pub/linux/kernel/people/will/docs/qemu/qemu-arm64-howto.html

if [ ! -f esp/EFI/boot/bootaa64.efi ]; then
  mkdir -p esp/EFI/boot
  ln -s ../../../../target/aarch64-unknown-uefi/debug/cosmos.efi esp/EFI/boot/bootaa64.efi
fi

if [ ! -f disk.img ]; then
  qemu-img create -f qcow2 disk.img 16G
fi

if [ ! -f varstore.img ]; then
  truncate -s 64m varstore.img
fi

if [ ! -f efi.img ]; then
  truncate -s 64m efi.img
  dd if=/usr/share/qemu-efi-aarch64/QEMU_EFI.fd of=efi.img conv=notrunc
fi

qemu-system-aarch64 -M virt  \
      -machine virtualization=true -machine virt,gic-version=3  \
      -cpu cortex-a76 -smp 2 -m 4096           \
      -drive if=pflash,format=raw,file=efi.img,readonly=on      \
      -drive if=pflash,format=raw,file=varstore.img         \
      -drive format=raw,file=fat:rw:esp \
      -drive if=virtio,format=qcow2,file=disk.img           \
      -device virtio-scsi-pci,id=scsi0              \
      -object rng-random,filename=/dev/urandom,id=rng0      \
      -device virtio-rng-pci,rng=rng0               \
      -device virtio-net-pci,netdev=net0                \
      -netdev user,id=net0,hostfwd=tcp::8022-:22            \
      -nographic                            
